### PR TITLE
Future-request plugin

### PR DESCRIPTION
**Pull request by dkeysil**
Feature requests plugin:

1. Create feature requests with title, description and start amount of sats
2. Publish list of feature requests
3. Possibility to upvote feature request with sats

TODO:

- [x] 1. Test payment receiving (can't do that because infinity.lnbits.com doesn't receive any payments and I still don't have my own node)
- [x] 2. Design improvements
- [ ] 3. Front-end code refactor
- [x] 4. Sorting issue - I set DESC sort by sats, but it doesn't work

p.s. and sorry for my formatter

### CODE REVIEW

**Comment by fiatjaf** [comment]
Are you running some autoformatter on the entire repository? What is it?

**Comment by dkeysil** [comment]
> Are you running some autoformatter on the entire repository? What is it?

Yeah, there are formatters coming with plugins in vscode
For lua: https://marketplace.visualstudio.com/items?itemName=sumneko.lua
For HTML: default vscode plugin I think

And before making this PR ready I think I'll rollback formatter in the old files

**Comment by dkeysil** [comment]
You can check latest version here:
https://lnbits.lnnn.shop/ext/ep1z34svz/aHR0cDovLzE5NC4xNjMuMTUyLjE2MTo4MDAwL2ZlYXR1cmUtcmVxdWVzdHMvZmVhdHVyZS1yZXF1ZXN0cy5sdWE/?

**Comment by fiatjaf** [comment]
I tested and it seems to work but I can't pay the invoices.

**Comment by fiatjaf** [comment]
@hsjoberg @engenegr do you think you could use this instead of the Etleneum contract?

**Comment by dkeysil** [comment]
@fiatjaf it's still in draft because I have bugs with invoice creation. I'm in progress ant will notify when it's will be ok

**Comment by dkeysil** [comment]
Some updates:
1. I'm updated the front part, made it a bit friendly
2. Fixed all bugs (glory to debug messages), now it's working as expected, try it!

**Comment by dkeysil** [comment]
Okay, everything works fine, I added notifications when user upvoting and creating requests.

There is kind of sucky design, if you have any advices - you are welcome.

Version with working invoices here - https://infinity.fiatjaf.com/ext/s46mzpaxr/aHR0cDovLzE5NC4xNjMuMTUyLjE2MTo4MDAwL2ZlYXR1cmUtcmVxdWVzdHMvZmVhdHVyZS1yZXF1ZXN0cy5sdWE/

**Comment by fiatjaf** [comment]
I don't care about the design. It is fine for me. We can improve that later over time. Actually it's better to leave it shitty so each user can customize the design as they please.

The only thing I would change is: do not create invoices as people click on "Description". If they just want to browse and read stuff around we shouldn't be wasting invoices on them. Make them select and amount then click a button to "pay" before you generate the invoice.

Unfortunately these invoices are all stateful and they use some storage every time they are created, so we have to save on that by not creating more than strictly necessary.

But I'm fine merging it like this and tweaking later if you're tired of this module and want to do other things with your life for now.

**Comment by dkeysil** [comment]
I'm removed invoice generating on description opening. If everything else is fine - let's merge it!

**Comment by evd0kim** [comment]
@fiatjaf I tried to test couple of links here and i do not see anything but errors from jsons in my browser.

**Comment by dkeysil** [comment]
@engenegr can you show logs please?

**Comment by evd0kim** [comment]
@dkeysil like this?

```
failed to get app settings: failed to get app code: http call errored: Get "http://194.163.152.161:8000/feature-requests/feature-requests.lua": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```

**Comment by fiatjaf** [comment]
We must come up with a better way of hosting both Infinity and the modules source code.

**Pull request closed without merging**
